languageCode = "en-us"
title = "Jim's Photo Blog"
baseURL = "http://localhost:1313/"
theme = "massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

 [params]
  # set below parameter to define a favicon
  favicon = "jt-favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
[params.posts]
     folderName = "post"
     pageSize = "4"
     featuredPost = true
     paginationPages = 5
     showFirstLast = true
 
[languages]
[languages.en]
  languageName = "English"
